// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgrhnbpzrwtqnqqvczcr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhncmhuYnB6cnd0cW5xcXZjemNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2MjU4OTYsImV4cCI6MjA3NjIwMTg5Nn0.GiIcaYZrqFfvgvDivyzveqUJU38HWDN7pmz-icp5Bkg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});